# -*- coding: utf-8 -*-
"""Untitled77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXffQtsy4kw_okuULYRDTtjD4-2mLUU6
"""

!pip install requests pandas google-cloud-bigquery google-cloud-bigquery-storage pyarrow db-dtypes python-dotenv

from google.colab import auth
auth.authenticate_user()
print("Authenticated successfully ✅")

GCP_PROJECT_ID = "ethereal-entity-497807-b5"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config.py
# 
# import os
# 
# # ---------------------------------------------------------------------------
# # API Settings — Open-Meteo (no API key required)
# # ---------------------------------------------------------------------------
# 
# API_BASE_URL = "https://api.open-meteo.com/v1/forecast"
# 
# LOCATIONS = [
#     {"name": "London",     "latitude": 51.5074,  "longitude": -0.1278,  "timezone": "Europe/London"},
#     {"name": "Manchester", "latitude": 53.4808,  "longitude": -2.2426,  "timezone": "Europe/London"},
#     {"name": "Mumbai",     "latitude": 19.0760,  "longitude": 72.8777,  "timezone": "Asia/Kolkata"},
#     {"name": "Delhi",      "latitude": 28.6139,  "longitude": 77.2090,  "timezone": "Asia/Kolkata"},
#     {"name": "New York",   "latitude": 40.7128,  "longitude": -74.0060, "timezone": "America/New_York"},
# ]
# 
# HOURLY_VARIABLES = [
#     "temperature_2m",
#     "apparent_temperature",
#     "precipitation",
#     "windspeed_10m",
#     "weathercode",
#     "relativehumidity_2m",
#     "cloudcover",
#     "uv_index",
# ]
# 
# PAST_DAYS                = 1
# REQUEST_TIMEOUT_SECONDS  = 30
# MAX_RETRIES              = 3
# RETRY_BACKOFF_SECONDS    = 5
# 
# # ---------------------------------------------------------------------------
# # BigQuery Settings — hardcoded for Colab
# # ---------------------------------------------------------------------------
# 
# GCP_PROJECT_ID   = "ethereal-entity-497807-b5"   # ← your project ID
# BIGQUERY_DATASET = "marketing_weather"
# BIGQUERY_TABLE   = "hourly_conditions"
# 
# BQ_TABLE_FULL_ID     = f"{GCP_PROJECT_ID}.{BIGQUERY_DATASET}.{BIGQUERY_TABLE}"
# BQ_WRITE_DISPOSITION = "WRITE_APPEND"
# 
# # ---------------------------------------------------------------------------
# # Derived Field Thresholds
# # ---------------------------------------------------------------------------
# 
# IDEAL_TEMP_MIN    = 15.0
# IDEAL_TEMP_MAX    = 28.0
# RAIN_THRESHOLD    = 1.0
# WIND_THRESHOLD    = 30.0
# UV_HIGH_THRESHOLD = 6
# 
# # ---------------------------------------------------------------------------
# # Logging
# # ---------------------------------------------------------------------------
# 
# LOG_LEVEL       = "INFO"
# LOG_FORMAT      = "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
# LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fetch.py
# 
# import logging
# import time
# from typing import Optional
# 
# import requests
# from requests.exceptions import ConnectionError, ReadTimeout, HTTPError
# 
# from config import (
#     API_BASE_URL,
#     HOURLY_VARIABLES,
#     LOCATIONS,
#     MAX_RETRIES,
#     PAST_DAYS,
#     REQUEST_TIMEOUT_SECONDS,
#     RETRY_BACKOFF_SECONDS,
# )
# 
# logger = logging.getLogger(__name__)
# 
# 
# class APIFetchError(Exception):
#     pass
# 
# 
# def _build_params(location: dict) -> dict:
#     return {
#         "latitude":      location["latitude"],
#         "longitude":     location["longitude"],
#         "hourly":        ",".join(HOURLY_VARIABLES),
#         "timezone":      location["timezone"],
#         "past_days":     PAST_DAYS,
#         "forecast_days": 1,
#     }
# 
# 
# def fetch_location(location: dict) -> Optional[dict]:
#     params = _build_params(location)
#     city   = location["name"]
# 
#     for attempt in range(1, MAX_RETRIES + 1):
#         try:
#             logger.info(f"Fetching {city} (attempt {attempt}/{MAX_RETRIES})")
# 
#             response = requests.get(
#                 API_BASE_URL,
#                 params=params,
#                 timeout=REQUEST_TIMEOUT_SECONDS,
#             )
#             response.raise_for_status()
#             data = response.json()
# 
#             if "hourly" not in data:
#                 raise ValueError(f"'hourly' key missing in response for {city}")
# 
#             logger.info(f"Fetched {len(data['hourly']['time'])} records for {city} ✅")
#             return data
# 
#         except (ConnectionError, ReadTimeout) as e:
#             logger.warning(f"Network error for {city} attempt {attempt}: {e}")
#             if attempt < MAX_RETRIES:
#                 time.sleep(RETRY_BACKOFF_SECONDS)
# 
#         except HTTPError as e:
#             status = e.response.status_code if e.response else "unknown"
#             logger.error(f"HTTP {status} for {city}: {e}")
#             if e.response and 400 <= e.response.status_code < 500:
#                 raise APIFetchError(f"Client error {status} for {city}") from e
#             if attempt < MAX_RETRIES:
#                 time.sleep(RETRY_BACKOFF_SECONDS)
# 
#         except ValueError as e:
#             logger.error(f"Validation error for {city}: {e}")
#             raise APIFetchError(str(e)) from e
# 
#         except Exception as e:
#             logger.error(f"Unexpected error for {city}: {type(e).__name__}: {e}")
#             raise APIFetchError(f"Unexpected error for {city}") from e
# 
#     raise APIFetchError(f"Failed to fetch {city} after {MAX_RETRIES} attempts")
# 
# 
# def fetch_all_locations() -> list:
#     results = []
#     failed  = []
# 
#     for location in LOCATIONS:
#         try:
#             raw = fetch_location(location)
#             results.append({"location": location, "data": raw})
#         except APIFetchError as e:
#             logger.error(f"Skipping {location['name']}: {e}")
#             failed.append(location["name"])
# 
#     if failed:
#         logger.warning(f"Failed locations: {failed}")
#     else:
#         logger.info(f"All {len(results)} locations fetched successfully ✅")
# 
#     return results

# Commented out IPython magic to ensure Python compatibility.
# %%writefile transform.py
# 
# import logging
# from datetime import datetime
# from typing import Any
# 
# import pandas as pd
# 
# from config import (
#     IDEAL_TEMP_MAX,
#     IDEAL_TEMP_MIN,
#     RAIN_THRESHOLD,
#     UV_HIGH_THRESHOLD,
#     WIND_THRESHOLD,
# )
# 
# logger = logging.getLogger(__name__)
# 
# WMO_CODE_DESCRIPTIONS = {
#     0:  "Clear sky",
#     1:  "Mainly clear",
#     2:  "Partly cloudy",
#     3:  "Overcast",
#     45: "Foggy",
#     48: "Icy fog",
#     51: "Light drizzle",
#     53: "Moderate drizzle",
#     55: "Dense drizzle",
#     61: "Slight rain",
#     63: "Moderate rain",
#     65: "Heavy rain",
#     71: "Slight snow",
#     73: "Moderate snow",
#     75: "Heavy snow",
#     80: "Slight showers",
#     81: "Moderate showers",
#     82: "Violent showers",
#     95: "Thunderstorm",
#     96: "Thunderstorm with hail",
#     99: "Thunderstorm with heavy hail",
# }
# 
# 
# def _safe_float(value: Any, default: float = 0.0) -> float:
#     if value is None:
#         return default
#     try:
#         return float(value)
#     except (TypeError, ValueError):
#         return default
# 
# 
# def _safe_int(value: Any, default: int = 0) -> int:
#     if value is None:
#         return default
#     try:
#         return int(value)
#     except (TypeError, ValueError):
#         return default
# 
# 
# def _get_season(month: int, hemisphere: str = "north") -> str:
#     if hemisphere == "north":
#         if month in (12, 1, 2): return "Winter"
#         elif month in (3, 4, 5): return "Spring"
#         elif month in (6, 7, 8): return "Summer"
#         else: return "Autumn"
#     else:
#         if month in (12, 1, 2): return "Summer"
#         elif month in (3, 4, 5): return "Autumn"
#         elif month in (6, 7, 8): return "Winter"
#         else: return "Spring"
# 
# 
# def _campaign_viability_score(
#     temp, apparent_temp, precipitation, windspeed, uv_index, weathercode
# ) -> float:
#     score = 10.0
# 
#     if temp < IDEAL_TEMP_MIN:
#         score -= min(4.0, (IDEAL_TEMP_MIN - temp) * 0.2)
#     elif temp > IDEAL_TEMP_MAX:
#         score -= min(4.0, (temp - IDEAL_TEMP_MAX) * 0.2)
# 
#     if precipitation >= RAIN_THRESHOLD:
#         score -= min(5.0, precipitation * 2.0)
# 
#     if windspeed > WIND_THRESHOLD:
#         score -= min(3.0, (windspeed - WIND_THRESHOLD) * 0.1)
# 
#     if uv_index > UV_HIGH_THRESHOLD:
#         score -= 1.0
# 
#     if weathercode in (95, 96, 99):
#         score = 0.0
#     elif weathercode in (65, 75, 82):
#         score = max(0.0, score - 4.0)
# 
#     return round(max(0.0, min(10.0, score)), 2)
# 
# 
# def _classify_viability(score: float) -> str:
#     if score >= 8.0:   return "Excellent"
#     elif score >= 6.0: return "Good"
#     elif score >= 4.0: return "Fair"
#     elif score >= 2.0: return "Poor"
#     else:              return "Unsuitable"
# 
# 
# def transform_location(location_config: dict, raw_data: dict) -> pd.DataFrame:
#     city   = location_config["name"]
#     hourly = raw_data.get("hourly", {})
# 
#     if "time" not in hourly:
#         logger.error(f"No 'time' field for {city}. Skipping.")
#         return pd.DataFrame()
# 
#     times   = hourly["time"]
#     n       = len(times)
#     records = []
# 
#     logger.info(f"Transforming {n} records for {city}")
# 
#     for i in range(n):
#         try:
#             timestamp_str = times[i]
#             dt            = datetime.fromisoformat(timestamp_str)
# 
#             temp          = _safe_float(hourly.get("temperature_2m",      [None]*n)[i])
#             apparent_temp = _safe_float(hourly.get("apparent_temperature", [None]*n)[i])
#             precipitation = _safe_float(hourly.get("precipitation",        [None]*n)[i])
#             windspeed     = _safe_float(hourly.get("windspeed_10m",        [None]*n)[i])
#             weathercode   = _safe_int  (hourly.get("weathercode",          [None]*n)[i])
#             humidity      = _safe_float(hourly.get("relativehumidity_2m",  [None]*n)[i])
#             cloudcover    = _safe_float(hourly.get("cloudcover",           [None]*n)[i])
#             uv_index      = _safe_float(hourly.get("uv_index",             [None]*n)[i])
# 
#             weather_description = WMO_CODE_DESCRIPTIONS.get(weathercode, f"WMO code {weathercode}")
#             hemisphere          = "south" if location_config["latitude"] < 0 else "north"
#             season              = _get_season(dt.month, hemisphere)
#             day_type            = "Weekend" if dt.weekday() >= 5 else "Weekday"
# 
#             hour = dt.hour
#             if   6  <= hour < 12: time_of_day = "Morning"
#             elif 12 <= hour < 17: time_of_day = "Afternoon"
#             elif 17 <= hour < 21: time_of_day = "Evening"
#             else:                 time_of_day = "Night"
# 
#             viability_score = _campaign_viability_score(
#                 temp, apparent_temp, precipitation, windspeed, uv_index, weathercode
#             )
#             viability_label = _classify_viability(viability_score)
# 
#             if   apparent_temp < 0:  temp_feel = "Freezing"
#             elif apparent_temp < 10: temp_feel = "Cold"
#             elif apparent_temp < 18: temp_feel = "Cool"
#             elif apparent_temp < 25: temp_feel = "Comfortable"
#             elif apparent_temp < 32: temp_feel = "Warm"
#             else:                    temp_feel = "Hot"
# 
#             records.append({
#                 "city":                     city,
#                 "latitude":                 location_config["latitude"],
#                 "longitude":                location_config["longitude"],
#                 "timezone":                 location_config["timezone"],
#                 "timestamp":                timestamp_str,
#                 "date":                     dt.strftime("%Y-%m-%d"),
#                 "hour":                     hour,
#                 "day_of_week":              dt.strftime("%A"),
#                 "day_type":                 day_type,
#                 "season":                   season,
#                 "time_of_day":              time_of_day,
#                 "temperature_c":            temp,
#                 "apparent_temperature_c":   apparent_temp,
#                 "precipitation_mm":         precipitation,
#                 "windspeed_kmh":            windspeed,
#                 "humidity_pct":             humidity,
#                 "cloudcover_pct":           cloudcover,
#                 "uv_index":                 uv_index,
#                 "weathercode":              weathercode,
#                 "weather_description":      weather_description,
#                 "temp_feel":                temp_feel,
#                 "campaign_viability_score": viability_score,
#                 "campaign_viability_label": viability_label,
#                 "ingested_at":              datetime.utcnow().isoformat(),
#             })
# 
#         except Exception as e:
#             logger.warning(f"Skipping row {i} for {city}: {e}")
#             continue
# 
#     df = pd.DataFrame(records)
#     logger.info(f"Transform done for {city}: {len(df)} rows ✅")
#     return df
# 
# 
# def transform_all(fetched_results: list) -> pd.DataFrame:
#     all_frames = []
# 
#     for result in fetched_results:
#         df = transform_location(result["location"], result["data"])
#         if not df.empty:
#             all_frames.append(df)
# 
#     if not all_frames:
#         logger.error("No data to transform — all locations failed")
#         return pd.DataFrame()
# 
#     combined = pd.concat(all_frames, ignore_index=True)
#     logger.info(f"Combined: {len(combined)} rows across {combined['city'].nunique()} cities ✅")
#     return combined

# Commented out IPython magic to ensure Python compatibility.
# %%writefile load.py
# 
# import logging
# 
# import pandas as pd
# from google.api_core.exceptions import GoogleAPICallError, NotFound
# from google.cloud import bigquery
# from google.cloud.bigquery import SchemaField
# 
# from config import (
#     BQ_TABLE_FULL_ID,
#     BQ_WRITE_DISPOSITION,
#     BIGQUERY_DATASET,
#     GCP_PROJECT_ID,
# )
# 
# logger = logging.getLogger(__name__)
# 
# SCHEMA = [
#     SchemaField("city",                     "STRING",  mode="REQUIRED"),
#     SchemaField("latitude",                 "FLOAT64", mode="NULLABLE"),
#     SchemaField("longitude",                "FLOAT64", mode="NULLABLE"),
#     SchemaField("timezone",                 "STRING",  mode="NULLABLE"),
#     SchemaField("timestamp",                "STRING",  mode="REQUIRED"),
#     SchemaField("date",                     "DATE",    mode="NULLABLE"),
#     SchemaField("hour",                     "INTEGER", mode="NULLABLE"),
#     SchemaField("day_of_week",              "STRING",  mode="NULLABLE"),
#     SchemaField("day_type",                 "STRING",  mode="NULLABLE"),
#     SchemaField("season",                   "STRING",  mode="NULLABLE"),
#     SchemaField("time_of_day",              "STRING",  mode="NULLABLE"),
#     SchemaField("temperature_c",            "FLOAT64", mode="NULLABLE"),
#     SchemaField("apparent_temperature_c",   "FLOAT64", mode="NULLABLE"),
#     SchemaField("precipitation_mm",         "FLOAT64", mode="NULLABLE"),
#     SchemaField("windspeed_kmh",            "FLOAT64", mode="NULLABLE"),
#     SchemaField("humidity_pct",             "FLOAT64", mode="NULLABLE"),
#     SchemaField("cloudcover_pct",           "FLOAT64", mode="NULLABLE"),
#     SchemaField("uv_index",                 "FLOAT64", mode="NULLABLE"),
#     SchemaField("weathercode",              "INTEGER", mode="NULLABLE"),
#     SchemaField("weather_description",      "STRING",  mode="NULLABLE"),
#     SchemaField("temp_feel",                "STRING",  mode="NULLABLE"),
#     SchemaField("campaign_viability_score", "FLOAT64", mode="NULLABLE"),
#     SchemaField("campaign_viability_label", "STRING",  mode="NULLABLE"),
#     SchemaField("ingested_at",              "STRING",  mode="NULLABLE"),
# ]
# 
# 
# def _get_or_create_dataset(client: bigquery.Client) -> None:
#     dataset_ref             = bigquery.Dataset(f"{GCP_PROJECT_ID}.{BIGQUERY_DATASET}")
#     dataset_ref.location    = "US"
#     dataset_ref.description = "Marketing weather pipeline — hourly conditions for key cities."
#     try:
#         client.get_dataset(dataset_ref)
#         logger.info(f"Dataset '{BIGQUERY_DATASET}' already exists")
#     except NotFound:
#         client.create_dataset(dataset_ref, exists_ok=True)
#         logger.info(f"Created dataset '{BIGQUERY_DATASET}' ✅")
# 
# 
# def load_to_bigquery(df: pd.DataFrame) -> bool:
#     if df.empty:
#         logger.error("DataFrame is empty — nothing to load")
#         return False
# 
#     logger.info(f"Loading {len(df)} rows to {BQ_TABLE_FULL_ID}")
# 
#     try:
#         client = bigquery.Client(project=GCP_PROJECT_ID)
#         _get_or_create_dataset(client)
# 
#         if "date" in df.columns:
#             df["date"] = pd.to_datetime(df["date"]).dt.date
# 
#         job_config = bigquery.LoadJobConfig(
#             schema=SCHEMA,
#             write_disposition=BQ_WRITE_DISPOSITION,
#             ignore_unknown_values=False,
#             create_disposition="CREATE_IF_NEEDED",
#         )
# 
#         job = client.load_table_from_dataframe(df, BQ_TABLE_FULL_ID, job_config=job_config)
#         job.result()
# 
#         table = client.get_table(BQ_TABLE_FULL_ID)
#         logger.info(f"Load complete ✅ | Rows this run: {len(df)} | Total in table: {table.num_rows}")
#         return True
# 
#     except GoogleAPICallError as e:
#         logger.error(f"BigQuery API error: {e}")
#         return False
# 
#     except Exception as e:
#         logger.error(f"Unexpected load error: {type(e).__name__}: {e}")
#         return False

import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
print("Logging configured ✅")

from fetch import fetch_all_locations
from transform import transform_all
from load import load_to_bigquery

print("=" * 50)
print("STEP 1: FETCHING DATA")
print("=" * 50)
fetched = fetch_all_locations()
print(f"\n→ {len(fetched)} locations fetched\n")

print("=" * 50)
print("STEP 2: TRANSFORMING DATA")
print("=" * 50)
df = transform_all(fetched)
print(f"\n→ {len(df)} total rows transformed\n")

print("Preview of transformed data:")
print(df[['city','date','hour','temperature_c',
          'weather_description',
          'campaign_viability_score',
          'campaign_viability_label']].head(10).to_string(index=False))

print("\n" + "=" * 50)
print("STEP 3: LOADING TO BIGQUERY")
print("=" * 50)
success = load_to_bigquery(df)

print("\n" + "=" * 50)
if success:
    print("✅ PIPELINE COMPLETE — Data is in BigQuery!")
else:
    print("❌ PIPELINE FAILED — Check errors above")
print("=" * 50)

from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project="ethereal-entity-497807-b5")

query = """
    SELECT
        city,
        date,
        ROUND(AVG(temperature_c), 1)               AS avg_temp_c,
        ROUND(SUM(precipitation_mm), 2)             AS total_rain_mm,
        ROUND(AVG(campaign_viability_score), 2)     AS avg_viability_score,
        MAX(campaign_viability_score)               AS peak_viability_score,
        COUNTIF(campaign_viability_score >= 6.0)    AS good_hours_count,
        COUNTIF(campaign_viability_score >= 8.0)    AS excellent_hours_count
    FROM `ethereal-entity-497807-b5.marketing_weather.hourly_conditions`
    GROUP BY city, date
    ORDER BY avg_viability_score DESC
"""

result = client.query(query).to_dataframe()
print("=" * 60)
print("QUERY RESULT — Daily Campaign Viability by City")
print("=" * 60)
print(result.to_string(index=False))

query2 = """
    SELECT
        city,
        COUNT(*)                                         AS total_hours,
        ROUND(AVG(campaign_viability_score), 2)          AS avg_score,
        COUNTIF(campaign_viability_label = 'Excellent')  AS excellent_hours,
        COUNTIF(campaign_viability_label = 'Good')       AS good_hours,
        COUNTIF(campaign_viability_label = 'Poor')       AS poor_hours,
        ROUND(
            100.0 * COUNTIF(campaign_viability_score >= 6.0) / COUNT(*), 1
        )                                                AS pct_usable_hours
    FROM `ethereal-entity-497807-b5.marketing_weather.hourly_conditions`
    GROUP BY city
    ORDER BY avg_score DESC
"""

result2 = client.query(query2).to_dataframe()
print("=" * 60)
print("CITY RANKINGS — Best Cities for Outdoor Campaigns")
print("=" * 60)
print(result2.to_string(index=False))